# Generated by Django 5.2.8 on 2026-01-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category_add',
            new_name='category_model',
        ),
    ]
