# Generated by Django 5.2.8 on 2026-01-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_rename_category_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='image/')),
                ('cat_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category_model')),
            ],
        ),
    ]
